### ISSUE TITLE
Feature Request: Improved line plotting functions with interactive smoothing

### ISSUE THREAD

**Issue by cwkx** [fossasia/visdom#18]
I think it would be good if it could support better line plotting like with tensorboards writer.add_summary summary.scalar:

1) append single data points at a time
2) interactive smoothing slider for line plots ( e.g. with https://plot.ly/python/slider-widget/ )
3) transparent view of non-smoothed data 
4) error envelopes ( https://plot.ly/python/continuous-error-bars )
5) logging of relative/wall time simultaneous to global steps in x-axis

**Comment by episodeyang** [comment]
it looks like this will be difficult without updating plot.ly library.

**Comment by ajabri** [comment]
It's becoming increasingly clear that it might be worth it to assemble some utility functions. E.g, for the continuous error bars, something along the lines of:

```python
def make_errors(ys,xs=None, color=None, name=None):
    if xs is None:
        xs = [list(range(len(y))) for y in ys]

    minX = min([len(x) for x in xs])

    xs = [x[:minX] for x in xs]
    ys = [y[:minX] for y in ys]

    assert all([(len(y) == len(ys[0])) for y in ys]), \
        'Y should be the same size for all traces'

    assert all([(x == xs[0]) for x in xs]), \
        'X should be the same for all traces'

    y = np.array(ys)
    yavg = np.mean(y, 0)
    ystd = np.std(y, 0)

    err_traces = [
        dict(x=xs[0], y=yavg.tolist(), mode='lines', name=name,
            line=dict(color=color)),
        dict(
            x=xs[0] + xs[0][::-1],
            y=(yavg + ystd).tolist() + (yavg - ystd).tolist()[::-1],
            fill='tozerox',
            fillcolor=(color[:-1] + str(', 0.2)')).replace('rgb', 'rgba')
                        if color is not None else None,
            line=dict(color='transparent'),
            name=name + str('_error') if name is not None else None,
        )
    ]

    return err_traces, xs, ys
```

**Comment by dizcza** [comment]
@ajabri, how to send these traces in Visdom?
I image something like viz._send(err_traces, ...?)

**Comment by Spandan-Madan** [comment]
Does the closed issue mean that these have been incorporated? Or that accepting it as an "enhancement" is enough to close the issue?

I would like the smooth interpolated curve functionality quite a lot.

**Comment by rmehta1987** [comment]
@dizczaif if you still need to know, to send traces to plotly you need to do:

```
viz._send({'data': err_traces, 'layout': layout, 'win': 'mywin'})
```

also you need to include the type of plot so, the dicts should should be:

```
dict(x=xs[0], y=yavg.tolist(), mode='lines', type='line' name=name,
            line=dict(color=color))
```
