### ISSUE TITLE
support newlines in plot.text

### ISSUE THREAD

**Issue by dizcza** [fossasia/visdom#476]
Is there a way to add many lines in `viz.text` at once? If my text has `\n` symbols, they are removed by visdom engine. I saw https://github.com/facebookresearch/visdom/issues/35 issue but it was marked as fixed and I still cannot print newlines.

`viz.text('Hello\r\nmighty\r\nvisdom!')` clashes three lines in one like so:
![screenshot from 2018-09-16 22-20-59](https://user-images.githubusercontent.com/7688337/45600038-d5869980-b9fe-11e8-9f99-4763f3c851e9.png)

I'd like to have them separated, line by line. If I download the text from the window, it does list three lines, not one. So I don't know if it's a bug or not supported feature.

Visdom version 0.1.8.5.

Updated.
I know that I can use for loop. But in cases when I have 100 lines to push to the remote visdom server, for some reason, one line is pushed very slow so I'm forced to wait while all my text appears...

**Comment by lvdmaaten** [comment]
Did you try using <br> rather than \n?
