### ISSUE TITLE
Feature Request: Sunburst Chart

### ISSUE THREAD

**Issue by dehoyosb** [fossasia/visdom#700]
Hello everybody, i have been using visdom for a while now and i have found to be a very useful tool to show results and some analytics. However, reacently i have created a Sunburst chart to plot some hierarchical dependencies that my dataset has, but i havent found a way to expose the graph in visdom. 
I believe it is not implemented currently, so i would like to request this new feature. Nevertheless, if there is a way to expose the graph, i'd really appreciate the help

Thank you very much!

**Comment by JackUrb** [comment]
In theory this would be possible to implement (as plotly supports [sunburst charts](https://plot.ly/javascript/sunburst-charts/)) but we haven't directly implemented them yet. In the meantime, you can use the `data` and `layout` sets shown in the linked example and call the generic send as described in [our docs](https://github.com/facebookresearch/visdom#generic-plots).

**Comment by ath34-tech** [comment]
Checkout my solution!

**Comment by ath34-tech** [comment]
Hey @JackUrb ,please checkout my pull request,
Thank you!

**Comment by ath34-tech** [comment]
Hey there, 
I opened a pull request yesterday, want to know should I can make the layout customizable too or not?
thank you!
Please merge my PR if it is ok.

**Comment by JackUrb** [comment]
Sorry, but I won't be reviewing things until Monday.

**Comment by ath34-tech** [comment]
@JackUrb can you assign this issue to me, and review my PR so that I can work on other open issues.
Thank you!

**Comment by ath34-tech** [comment]
Thanks for assigning
 and please review the pull request too!

**Comment by JackUrb** [comment]
@ath34-tech Thanks for implementing this functionality!
