### ISSUE TITLE
Please indicate somewhere what the "opts" variable actually is for Python

### ISSUE THREAD

**Issue by kirpi-1** [fossasia/visdom#704]
Please indicate somewhere (maybe under https://github.com/facebookresearch/visdom#customizing-plots) that "opts" (the input options variable) is a dictionary for Python. I was very confused for a very long time because it appeared as though I had to use a named tuple to create an opts object with dot notation, or that there existed some undocumented visdom.options() class that would instantiate an options object that I could modify.

**Comment by JackUrb** [comment]
Closed in #820
