### ISSUE TITLE
Image Link in README broken

### ISSUE THREAD

**Issue by mnagel** [fossasia/visdom#743]
In README.md you have

```
Visdom aims to facilitate visualization of (remote) data with an emphasis on supporting scientific experimentation.

<p align="center"><img src="https://lh3.googleusercontent.com/-h3HuvbU2V0SfgqgXGiK3LPghE5vqvS0pzpObS0YgG_LABMFk62JCa3KVu_2NV_4LJKaAa5-tg=s0" width="500"  /></p>
```

Which looks like:

<p align="center"><img src="https://lh3.googleusercontent.com/-h3HuvbU2V0SfgqgXGiK3LPghE5vqvS0pzpObS0YgG_LABMFk62JCa3KVu_2NV_4LJKaAa5-tg=s0" width="500"  /></p>

i.e. broken image, http code 400

**Comment by nlok5923** [comment]
Working on it.

**Comment by nlok5923** [comment]
@mariobehling  sir please can you provide me the correct image link.

**Comment by JackUrb** [comment]
We have removed this link, as we are not sure what was originally behind it anymore.
