### ISSUE TITLE
get_env_list raises TypeError in offline mode

### ISSUE THREAD

**Issue by vfdev-5** [fossasia/visdom#749]
**Bug Description**
If call `get_env_list()` in offline mode, it raises `TypeError`.

**Reproduction Steps**
```python
>>> import visdom
>>> vis = visdom.Visdom(offline=True, log_to_filename="/tmp/log.visdom")
>>> vis.get_env_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/visdom/__init__.py", line 822, in get_env_list
    return json.loads(self._send({}, endpoint='env_state', quiet=True))
  File "/opt/conda/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not bool
```

**Comment by JackUrb** [comment]
In offline mode, we don't even send anything to the frontend:
https://github.com/fossasia/visdom/blob/e0a912d39f88e637f483c229c0fbf3d4da119ac5/py/visdom/__init__.py#L680-L682
As such, in offline mode we'd probably need to be keeping track of a local env list to solve this problem. You could do so right in the above location, intercepting sends that are setting different `env`s.

**Comment by ath34-tech** [comment]
Ya, I thought the same,  can you point what function is responsible for creating env? 
I am thinking that whenever env is created we will add its data to the list and return that list. Or there is something that work different and I am still missing some point then please tell me.
Thank you!

**Comment by JackUrb** [comment]
The local client doesn't do anything to create a new env, or create them itself, it has to do with the `env` value set by the time the `send` method is called. The server then creates an env.

**Comment by ath34-tech** [comment]
Hey there,i manage to solve this issue, please check if it is right or wrong. 
Thank you!

**Comment by ath34-tech** [comment]
hey @JackUrb , please review:https://github.com/fossasia/visdom/pull/824
thank you!

**Comment by ath34-tech** [comment]
Hey @JackUrb I made changes to PR, please check them,
Thank you!

**Comment by ath34-tech** [comment]
Hey @JackUrb , i formatted the code, please check if it is working.

**Comment by ath34-tech** [comment]
Hey @JackUrb , please check my code on latest commit.

**Comment by ath34-tech** [comment]
@JackUrb Please merge my PR.thank you

**Comment by ath34-tech** [comment]
Hey @JackUrb  i removed whitespaces , please merge my PR now.
Thank you

**Comment by ath34-tech** [comment]
Hey @JackUrb please close this issue
