### ISSUE TITLE
Edit button does not work anymore

### ISSUE THREAD

**Issue by mehrdad-h** [fossasia/visdom#763]
The edit button at the bottom right of the charts is not working now. According to [plot.ly](https://community.plotly.com/t/url-change-for-chart-studio-cloud-https-chart-studio-plotly-com/33557) the link in the edit button (below) should be changed from `https://plot.ly` to `https://chart-studio.plotly.com` in order for the charts to be imported to the cloud.

https://github.com/facebookresearch/visdom/blob/42e86df503f4db3ce965db79ff08f23d6360b6e4/py/visdom/static/index.html#L55

**Comment by JackUrb** [comment]
Thanks for the heads up @mehrdad-h! We'll be able to handle this soon.

**Comment by ath34-tech** [comment]
I think this issue is resolved, maybe you should close it, and if it is not  resolve yet then please let me know what is expected behaviour.

**Comment by JackUrb** [comment]
@ath34-tech are you saying that the edit button currently does link to being able to edit a plot in plotly?

**Comment by ath34-tech** [comment]
> @ath34-tech are you saying that the edit button currently does link to being able to edit a plot in plotly?

Yes right, if you see it is a link now which open in plotly where you can edit the graph.

**Comment by JackUrb** [comment]
Confirmed - thanks for identifying @ath34-tech.
