### ISSUE TITLE
Cannot plot to environments with `/` in name 

### ISSUE THREAD

**Issue by shubham-goel** [fossasia/visdom#776]
**Bug Description**
Visdom doesn't plot to environments with `/` in their name. Instead, it redirects the plot to an alternate environment name where `/` is replaced by `_`.

**Reproduction Steps**
```python
import visdom
vis = visdom.Visdom(port=6010, env='a/b')
# An empty environment with name  `a/b` is created. See screenshot 1.

vis.text('Hello, world!')
# The original environment `a/b` is still visible but blank. See Screenshot 2.
# The "Hello, world!" window appears in a new environment `a_b`. See Screenshot 3. 
```

**Expected behavior**
I expect the "Hello, world!" window to show up in the `a/b` environment.

**Screenshots**
Screenshot 1
<img width="1784" alt="Screen Shot 2021-01-04 at 9 19 38 PM" src="https://user-images.githubusercontent.com/11925282/103599767-ea3f1200-4ed3-11eb-95c0-ecee4719ff20.png">

Screenshot 2
<img width="1781" alt="Screen Shot 2021-01-04 at 9 19 50 PM" src="https://user-images.githubusercontent.com/11925282/103599780-f034f300-4ed3-11eb-9f23-1767a88e79c4.png">

Screenshot 3
<img width="1786" alt="Screen Shot 2021-01-04 at 9 20 06 PM" src="https://user-images.githubusercontent.com/11925282/103599786-f62ad400-4ed3-11eb-9d27-9a3459dc592c.png">

**Client logs:**
```
main.js:95 Download the React DevTools for a better development experience: https://fb.me/react-devtools
:6310/extensions/MathMenu.js?V=2.7.1:2 Uncaught SyntaxError: Unexpected number
:6310/extensions/MathZoom.js?V=2.7.1:2 Uncaught SyntaxError: Unexpected number
DevTools failed to load SourceMap: Could not load content for http://localhost:6310/static/js/layout-bin-packer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:6310/static/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.js?v=512fa4c894cc296b44e8ec1c28524a962a0f013eaeb1cba03250e343049fb3ec11a36372fb43eeac66a88e08212644a4aae16c2f5d213db6a80457607cb1f8ac:48 [Violation] 'setTimeout' handler took 54ms
[Violation] Forced reflow while executing JavaScript took 41ms
```

**Server logs:**
```
$ visdom -p 6010
Checking for scripts.
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:6010
INFO:tornado.access:304 GET / (::1) 19.70ms
INFO:tornado.access:304 GET /favicon.png (::1) 17.70ms
INFO:tornado.access:101 GET /socket (::1) 0.36ms
INFO:root:Opened new socket from ip: ::1
INFO:tornado.access:200 POST /env/a/b (::1) 0.60ms
INFO:tornado.access:200 POST /env/a/b (::1) 0.60ms
INFO:tornado.access:304 GET /extensions/MathMenu.js?V=2.7.1 (::1) 16.96ms
INFO:tornado.access:304 GET /extensions/MathZoom.js?V=2.7.1 (::1) 19.47ms
WARNING:tornado.access:404 GET /static/js/layout-bin-packer.js.map (::1) 7.42ms
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map (::1) 0.40ms
INFO:tornado.access:200 POST /env/a/b (100.96.161.120) 0.41ms
INFO:tornado.access:101 GET /vis_socket (100.96.161.120) 0.33ms
INFO:root:Opened visdom socket from ip: 100.96.161.120
INFO:tornado.access:200 POST /events (100.96.161.120) 0.50ms
INFO:tornado.access:200 POST /env/a_b (::1) 0.47ms
```

**Additional context**
N/A

**Comment by JackUrb** [comment]
Hi @shubham-goel, thanks for opening an issue!

This is a product of our first design - all environment `.json` files were to be stored in the specified folder, but allowing `/` in the filename would lead to issues in addressing the files. As such we just replaced those (and other special characters) with `_`. That character is also used as the delimiter in the selector, allowing the grouped dropdowns. The only unexpected behavior I see is that `a/b` actually appears as a possible env in the selector.

One could certainly expand this to allow subdirectories of the environment directory if they'd like to.

**Comment by shubham-goel** [comment]
Thanks for your response @JackUrb! I now understand the expected behavior. There's certainly a plethora of features that could be build to improve visdom, I wish we had the time to implement them all :)

Closing this issue since it's not an important feature enhancement.
