### ISSUE TITLE
Create a project logo 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/visdom#783]
The project does not have a logo yet. A simple text logo using a freely licensed font would be a great start.

**Comment by yashsehgal** [comment]
Hey @mariobehling, I am interested in this issue. Can you please assign me this?

**Comment by mariobehling** [comment]
We are not assigning issues to external contributors. Please mention that you would like to work on the issue and make a pull request to resolve it shortly after. Thanks.

**Comment by yashsehgal** [comment]
> We are not assigning issues to external contributors. Please mention that you would like to work on the issue and make a pull request to resolve it shortly after. Thanks.

Got it.

**Comment by nidhi8686** [comment]
I made three logos for the project.  Hope you'll like it

![b69022eb-13b5-4298-b79f-f84e8fb28575_200x200](https://user-images.githubusercontent.com/43919764/104812892-708c1a00-582b-11eb-8a43-f97db885432d.png)

![64a5bc9f-77e2-4c77-a37f-15a107388249_200x200](https://user-images.githubusercontent.com/43919764/104812896-7550ce00-582b-11eb-8b2c-9a0ef858c64a.png)

![2ae2c549-a878-4c5c-9887-1b91a94d47f2_200x200](https://user-images.githubusercontent.com/43919764/104812953-e09aa000-582b-11eb-9f41-313befd323b9.png)

**Comment by norbusan** [comment]
Codeheat?

The project has a different name ..

**Comment by nidhi8686** [comment]
The logo should be named Visdom?

**Comment by yashsehgal** [comment]
This might be more relevant.
![image](https://user-images.githubusercontent.com/62352288/104831111-a8d33d00-58ab-11eb-9745-d8af947c5056.png)

**Comment by norbusan** [comment]
@yashsehgal bit better, thanks

**Comment by yashsehgal** [comment]
So may I share the Figma Link to this file?

**Comment by himanshujaidka** [comment]
> The logo should be named Visdom?

Please go through the documentation

**Comment by adit4455** [comment]
How is it
![PicsArt_01-22-07 40 43](https://user-images.githubusercontent.com/70281937/105501098-cceab000-5ce9-11eb-8185-492204ff4e20.jpg)

**Comment by elioqoshi** [comment]
@mariobehling here are 2 proposals from my side:

![image](https://user-images.githubusercontent.com/5436686/106036634-e1f28500-60d5-11eb-92f3-26a40ab451e2.png)

**Comment by sudojarvis** [comment]
I would like to work on this issue.

**Comment by JackUrb** [comment]
I'm unsure why we haven't followed through on this earlier. @elioqoshi if you're still interested, these designs look great to me. I'd probably go with the more rectangular one (as it's closer in form to plots, but the rounded corners are still nice aesthetically).

**Comment by elioqoshi** [comment]
@JackUrb Thanks! Yeah I don't know what happened. @mariobehling asked me last year if I wanted to draft something up but then I never got a reply.

Anyway, I exported the 2nd logo for you in color, monochrome and horizontal and vertical versions as well :)

[Visdom Logo.zip](https://github.com/fossasia/visdom/files/7820306/Visdom.Logo.zip)
