### ISSUE TITLE
button side by side

### ISSUE THREAD

**Issue by back920096** [fossasia/visdom#784]
in properties 

Is there a way to make 2 buttons side by side with 2 menus side by side?

**Comment by JackUrb** [comment]
Sorry for the late response here, though there's not really enough context for me to understand what you're looking for. At the moment properties panes only handle the types of inputs we display in the demo:
https://github.com/fossasia/visdom/blob/master/example/demo-properties.py#L63-L67
You could feasibly add more types to be able to add additional functionality, but I'm not sure this is a priority.
