### ISSUE TITLE
Move images from Readme to /docs/images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/visdom#785]
The images in the Readme are loading from different sources including some from Google drives. To follow best practices please move them to a folder at /docs/images, please and correct the links in the Readme.

**Comment by iamsdas** [comment]
Working on it.

**Comment by iamsdas** [comment]
@mariobehling the second image in the README seems to be a dead link. Should I leave it as is?

**Comment by mariobehling** [comment]
Please delete dead links. If images have cryptic names please rename them to visdom-project-1.jpg/png etc.

**Comment by iamsdas** [comment]
Is the current way of naming alright?
Or should i rename them all to visdom-project-1..2..3 etc?

**Comment by iamsdas** [comment]
@mariobehling removed the dead link, could you review the PR?

**Comment by avats-dev** [comment]
I think this issue is resolved, right?

**Comment by JackUrb** [comment]
The images are now hosted directly on github in #888
