### ISSUE TITLE
Vis.surf

### ISSUE THREAD

**Issue by DuanhaoranCC** [fossasia/visdom#795]
Hello, I see the visdom function Vis.surf , but no relevant examples have been found. I want to draw error surface. I don't know what suggestions you have. Thank you very much.

**Comment by JackUrb** [comment]
Hi @DuanhaoranCC - the full extent of work we've done with surface so far is available in the demo:
https://github.com/fossasia/visdom/blob/master/example/demo.py#L263-L270

**Comment by DuanhaoranCC** [comment]
@JackUrb ,OK,Thank you very much for your help!

**Comment by ath34-tech** [comment]
Hey @JackUrb  if this issue is resolved then please close it. thank you!
