### ISSUE TITLE
Changing port does not work by visdom -port xxxx 

### ISSUE THREAD

**Issue by sekigh** [fossasia/visdom#801]
I want two independent visdom processes running on two different servers in parallel, sending visdom figures to a single local client by different ports, e.g. 8097 and 8098.  I want these setting because I accelerate a multiple number of processes in parallel. So what I did is as follows:

On visdom server A: visdom (with default port 8097)

On visdom server B: visdom -port 8098

But it looks that "visdom -port 8098" does not work at all. I traces visdom codes but it looks like not accepting command line arguments at all. How do I achieve my purpose?

Thank you for help.

**Comment by sekigh** [comment]
Additional Information:
My environment is as follows:

Server A: ubuntu16.04  ---> It works fine with "visdom" command
pytorch  1.3.1 cuda100py37h53c1284_0
visdom 0.1.8.9
ssh config with local forward port 8097

Server B: ubuntu 18.04  ---> I have a problem in "visdom -port 8098' after ssh Server B  
pytorch  1.8.1 py3.7_cuda11.1_cudnn8.0.5_0 
visdom 0.1.8.9
ssh config with local forward port 8098

**Comment by JackUrb** [comment]
Can you try explicitly running `server.py` (`python server.py -port 8098`)? The code that should pull this argument in is here:
https://github.com/fossasia/visdom/blob/master/py/visdom/server.py#L1799-L1801
And then use it here:
https://github.com/fossasia/visdom/blob/master/py/visdom/server.py#L1780

**Comment by sekigh** [comment]
Sorry for late response! I just read your message. I already tried visdom -port 8098 from server B again and succeeded in connection! Thank you.
