### ISSUE TITLE
How can I make Chinese texts displayed correctly rather than messy code?

### ISSUE THREAD

**Issue by LyuYuxin** [fossasia/visdom#808]
When I want to display a Chinese text it shows like this.
Use this to open other questions or issues, and provide context here.
![QQ截图20210702202116](https://user-images.githubusercontent.com/39041262/124274015-5644bf00-db73-11eb-9b84-b00f78c5d4c8.png)
Is this some kind of config error? 
What should I do ?

**Comment by cheekety** [comment]
This might be a UNICODE issue. Have you tried `encode('utf-8')` ?
