### ISSUE TITLE
`heatmap` append and more data cache/handling in visdom?

### ISSUE THREAD

**Issue by geyang** [fossasia/visdom#82]
Hi,

it looks like the both `line` and `scatter` has an `append` option in plotly, but `heatmap` does not.

In our experiment, we are using heatmap to render incoming streams of spectrum data, and it becomes quite slow to have to send over 100 kB of heatmap image for each additional column.

Is it within the scope of this project to add datacaching and functionalities like smoothing in this project?

If so, I can implement these inside this little helper module we use and make it available to everyone.

https://github.com/episodeyang/visdom_helper
Best,
Ge

**Comment by ajabri** [comment]
Hi @episodeyang !

Yes, you're right, its something that IMO should definitely be there. In general, I think it would be useful to have a plot object that can be updated efficiently; I suppose the question is where should the data caching happen -- server side, client side? I guess there are tradeoffs. If you do it on the server, you still have to send the whole thing to the browser. If you do it in the browser, the state won't be updated on the server. One solution could actually be to make the update on the server and just send a diff of the actual message string so it's cheaper. 

I actually indeed already came across your visdom_helper, it looks cool. If you're up for it, we're all for it!

Allan

**Comment by episodeyang** [comment]
@ajabri awesome! I'm up for it! I can keep the discussions here and link to the issues here!

**Comment by JackUrb** [comment]
Fixed in #834
