### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'asscalar'

### ISSUE THREAD

**Issue by Mahmood-Hussain** [fossasia/visdom#857]
**Bug Description**
AttributeError: module 'numpy' has no attribute 'asscalar'
numpy 1.23.0
visdom-0.1.8.9

**Reproduction Steps**
Enter steps to reproduce the behavior:
using the latest version of NumPy and when plotting heatmap

**Expected behavior**
plot heatmap

**Screenshots**
![image](https://user-images.githubusercontent.com/31275645/175867187-06354473-4dc7-4c7b-a123-e836415dbd50.png)

**Comment by da-h** [comment]
Hey there,

thanks for taking your time and submitting an issue. :)

Just looked into this and the error does not occur in the most recent visdom version.
Actually, I just checked the whole project for any occurrence of `asscalar` and it seems someone has already fixed all deprecations of this function.

Note, however, the most current version of visdom is not yet on pipy.org . (see #845 ).

Best,
*da-h*

**Comment by Mahmood-Hussain** [comment]
Thank You for your response it is also solved for me.
