### ISSUE TITLE
I would like to join this organisation

### ISSUE THREAD

**Issue by hemantwasthere** [fossasia/visdom#860]
Use this to open other questions or issues, and provide context here.

**Comment by JackUrb** [comment]
You'll have to go through [fossasia](https://fossasia.org/) to join the underlying organization. If you're interested in contributing to the project though, feel free to check some of the available issues or open a PR.

**Comment by hemantwasthere** [comment]
yeah what i have to do then @JackUrb

**Comment by JackUrb** [comment]
For joining fossasia or contributing? For the former, I'm not 100% sure what their workflow is. For the latter, feel free to ask about any of the available issues, especially those tagged with `help wanted` and `fix proposed`.

**Comment by hemantwasthere** [comment]
Okay, thanks @JackUrb 😊
