### ISSUE TITLE
Install visdom without Internet connection

### ISSUE THREAD

**Issue by KarhouTam** [fossasia/visdom#865]
I have used `pip install -e .` to install visdom itself through source code. However, visdom needs to download scripts additionally. And the target environment cannot connect to the Internet. What am I supposed to do to get through this?

**Comment by da-h** [comment]
Hey there,

easiest solution is probably to execute the `download.sh` script and then push the downloads placed in `py/static` folder to the machine without internet.

I think there should be a message somewhere that suggests exactly that in the event that no internet connection is available.

Best,
*da-h*

**Comment by KarhouTam** [comment]
I would try it. Thanks for your reply.

**Comment by da-h** [comment]
I will add a PR for this feature as soon as the refactoring of the server is done. (See #858).
