### ISSUE TITLE
Use visdom in Jupyter 

### ISSUE THREAD

**Issue by SmILeel** [fossasia/visdom#892]
**Bug Description**
When i use visdom in jupyter, I can not get the result on the visdom panel, and get ssome error info.

**Reproduction Steps**
Enter steps to reproduce the behavior:
1. I opened visdom server on my Ubantu server with  'python -m visdom.server -p 6006'
2. In jupyter notebook:  'import visdom; viz=visdom.Visdom(port=6006)'  and the server says 'INFO:root:Opened visdom socket from ip: 127.0.0.1' at the same time.
3. In jupyter notebook：‘viz.text('Hello, world!')’  but i can not get this text in visdom panel, but get some error info.
![visdom_error](https://user-images.githubusercontent.com/107383023/205541384-9abfcf88-8a91-4e35-bd2d-e8c663c60f2d.jpg)

**Expected behavior**
I should get the text in visdom panel, but it doesn't make any change.
![image](https://user-images.githubusercontent.com/107383023/205541706-ee49caf1-d249-479a-8c5d-3f3659be7755.png)

**Screenshots**

**Client logs:**
the jupyter returns 
'<?xml version="1.0" encoding="UTF-8" ?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">\n\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">\n\n<head>\n<title>500 Unable to connect</title>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n</head>\n\n<body>\n\n<h1>Unable to connect</h1>\n\n<p>Tinyproxy was unable to connect to the remote web server.</p>\n\n<hr />\n\n<p><em>Generated by <a href="https://tinyproxy.github.io/">tinyproxy</a> version 1.10.0.</em></p>\n\n</body>\n\n</html>\n'

**Server logs:**
Nothing reported by visdom.server and changed in visdom panel.

**Comment by da-h** [comment]
Hey there,

at least without tinyproxy, I cannot reproduce the issue with the commands you provided.
On my setup with `visdom==2.3.0` your example does show the text-window.

As I do not know tinyproxy and this does not seem to be related to be a visdom issue, I cannot give any support here.
But, as visdom relies on websockets for communication between server and client, did you maybe miss to include websocket upgrades (or related) in your proxy config?

As an alternative, you can try to use the visdom CLI-option `-use_frontend_client_polling` which could do the trick as well in your case.

Best,
*da-h*

**Comment by SmILeel** [comment]
Hi, dear sir,
I have tried to reinstall visdom in python and tinyproxy in Ubuntu, but it didn't work. Unluckily, as i am not so familiar with the mechanism of the whole architecture, i can not troubleshoot this problem. However, thanks for your help, and i would use matplotlib in jupyter notebook as an alternative.
best regards,
sz li
