### ISSUE TITLE
visdom绘制分类热力图

### ISSUE THREAD

**Issue by Lkevin20** [fossasia/visdom#913]
Use this to open other questions or issues, and provide context here.
为什么利用visdom.heatmap()绘制热力图时会出现平面图和峰图两种结果
![J3PLBA`ID6HA~`H8Y)E5C~V](https://user-images.githubusercontent.com/58387367/226530016-2038695e-9ad3-4551-bcfa-0a65656e8184.png)

**Comment by Lkevin20** [comment]
![D$4FD1S 9AS9W%)FIL@_NRI](https://user-images.githubusercontent.com/58387367/226530109-3b79316c-8be8-4585-8805-9864de55309f.png)

**Comment by da-h** [comment]
Hi,

to overwrite a window instead of creating a new one, use the `win` argument, i.e. `viz.heatmap(cls_show, win="my cls1 map)`.
(See https://github.com/fossasia/visdom#plotting-1)

Best,
*da-h*

**Comment by Lkevin20** [comment]
谢谢作者已解决。请问我如何画出作者您这样的能区分正负样本的分类得分散点图，我画的分类得分散点图无法直观区分正负样本











抢哥辣条还想跑
***@***.***






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fossasia/visdom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fossasia/visdom] visdom绘制分类热力图 (Issue #913)





 
Hi,
 
to overwrite a window instead of creating a new one, use the win argument, i.e. viz.heatmap(cls_show, win="my cls1 map).
 (See https://github.com/fossasia/visdom#plotting-1)
 
Best,
 da-h

**Comment by da-h** [comment]
I am sorry, but I do not understand chinese. But from what I got by using translate.google.com:
To create scatter plots, please see the [section `vis.scatter` in the Readme](https://github.com/fossasia/visdom/#visscatter), also there are some more examples in the file `example/components/plot_scatter.py` that could help.
